// <auto-generated />
using System;
using AtendimentoMedico.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtendimentoMedico.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataHoraChamada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraChegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataHoraFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroSequencial")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aguardando");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraChegada")
                        .HasDatabaseName("IX_Atendimentos_DataChegada");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_Atendimentos_PacienteId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Atendimentos_Status");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Especialidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Atendimento médico geral",
                            Nome = "Clinica Geral"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Especialidade do coração",
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Atendimento infantil",
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Tratamento de ossos e articulações",
                            Nome = "Ortopedia"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Cuidados com a pele",
                            Nome = "Dermatologia"
                        });
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Pacientes_Email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Pacientes_Nome");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Triagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraTriagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PressaoArterial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Triagens_AtendimentoId");

                    b.HasIndex("EspecialidadeId")
                        .HasDatabaseName("IX_Triagens_EspecialidadeId");

                    b.ToTable("Triagens", (string)null);
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("AtendimentoMedico.Core.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Triagem", b =>
                {
                    b.HasOne("AtendimentoMedico.Core.Domain.Entities.Atendimento", "Atendimento")
                        .WithOne("Triagem")
                        .HasForeignKey("AtendimentoMedico.Core.Domain.Entities.Triagem", "AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoMedico.Core.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Triagens")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Atendimento", b =>
                {
                    b.Navigation("Triagem");
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Especialidade", b =>
                {
                    b.Navigation("Triagens");
                });

            modelBuilder.Entity("AtendimentoMedico.Core.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
